/**
 * @brief This is the class to start all program and other modules.
 * 
 * @file launcher.h
 * @authors Generated by qt, modified by aleklnx
 * @date 2018-03-19
 */

#ifndef LAUNCHER_H
#define LAUNCHER_H
#include <QMainWindow>
#include <QListWidgetItem>

namespace Ui {
class Launcher;
}

class MemoryViewer;
class SocketManager;
class MemoryManager;

class Launcher : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Construct a new Launcher object
     * 
     * @param parent Is a pointer used by Qt.
     */
    explicit Launcher(QWidget *parent = 0);
    /**
     * @brief Destroy the Launcher object
     * 
     */
    ~Launcher();

private slots:

    void on_button_startServer_clicked();

    void on_button_quitApp_clicked();

    void on_button_test_clicked();

private:

    Ui::Launcher *ui;
    SocketManager * localServer;
    MemoryManager * menMan;
    MemoryViewer * monitor;
};

#endif // LAUNCHER_H
